export enum ErrorCodes{
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    INVALID_DATA = 'INVALID_DATA',
    INVALID_AADHAR = 'INVALID_AADHAR',
    INVALID_PAN = 'INVALID_PAN',
    INVALID_GST = 'INVALID_GST',
    INVALID_PHONE = 'INVALID_PHONE',
    INVALID_EMAIL = 'INVALID_EMAIL',
}